import React from 'react';
import { Receipt, Download, FileText, CheckCircle2 } from 'lucide-react';
import { Badge } from '@/components/ui/Badge';
import { cn } from '@/lib/utils';

export interface InvoiceItem {
  id: string;
  date: string;
  amount: number;
  status: 'paid' | 'pending' | 'failed';
  pdfUrl: string;
}

export interface InvoicesListProps {
  invoices: InvoiceItem[];
  className?: string;
}

export function InvoicesList({
  invoices,
  className,
}: InvoicesListProps) {
  return (
    <div
      className={cn(
        'overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-xs dark:border-zinc-800 dark:bg-zinc-950',
        className
      )}
    >
      <div className="border-b border-zinc-100 p-5 dark:border-zinc-900">
        <h3 className="text-sm font-semibold tracking-tight text-zinc-900 dark:text-zinc-100">
          Billing History &amp; Invoices
        </h3>
        <p className="mt-0.5 text-xs text-zinc-500 dark:text-zinc-400">
          Download PDF receipts and tax invoices generated by Stripe.
        </p>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left text-xs text-zinc-700 dark:text-zinc-300">
          <thead className="border-b border-zinc-200 bg-zinc-50/75 text-[11px] font-semibold uppercase tracking-wider text-zinc-500 dark:border-zinc-800 dark:bg-zinc-900/50 dark:text-zinc-400">
            <tr>
              <th className="px-4 py-3">Invoice</th>
              <th className="px-4 py-3">Billing Date</th>
              <th className="px-4 py-3">Amount</th>
              <th className="px-4 py-3">Status</th>
              <th className="px-4 py-3 text-right">Receipt</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-zinc-100 dark:divide-zinc-900">
            {invoices.map((inv) => (
              <tr
                key={inv.id}
                className="hover:bg-zinc-50/60 transition-colors dark:hover:bg-zinc-900/40"
              >
                <td className="px-4 py-3 font-mono font-semibold text-zinc-900 dark:text-zinc-100">
                  {inv.id}
                </td>
                <td className="px-4 py-3 font-mono text-zinc-500">
                  {new Date(inv.date).toLocaleDateString(undefined, {
                    month: 'short',
                    day: 'numeric',
                    year: 'numeric',
                  })}
                </td>
                <td className="px-4 py-3 font-mono font-bold text-zinc-900 dark:text-zinc-100">
                  {`$${inv.amount.toFixed(2)}`}
                </td>
                <td className="px-4 py-3">
                  <Badge
                    variant={inv.status === 'paid' ? 'emerald' : 'amber'}
                    size="sm"
                    dot
                  >
                    {inv.status === 'paid' ? 'Paid' : inv.status}
                  </Badge>
                </td>
                <td className="px-4 py-3 text-right">
                  <a
                    href={inv.pdfUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="inline-flex items-center gap-1 rounded-md p-1.5 text-zinc-400 hover:bg-zinc-100 hover:text-zinc-900 dark:hover:bg-zinc-800 dark:hover:text-zinc-100"
                    title="Download Receipt"
                  >
                    <Download className="h-3.5 w-3.5" />
                    <span className="text-[11px] font-medium">PDF</span>
                  </a>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default InvoicesList;
