// Package transport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package transport

// Defines values for TransportChangeMemberRoleRequestRole.
const (
	GrantAdmin  TransportChangeMemberRoleRequestRole = "admin"
	GrantMember TransportChangeMemberRoleRequestRole = "member"
	GrantOwner  TransportChangeMemberRoleRequestRole = "owner"
	GrantViewer TransportChangeMemberRoleRequestRole = "viewer"
)

// Valid indicates whether the value is a known member of the TransportChangeMemberRoleRequestRole enum.
func (e TransportChangeMemberRoleRequestRole) Valid() bool {
	switch e {
	case GrantAdmin:
		return true
	case GrantMember:
		return true
	case GrantOwner:
		return true
	case GrantViewer:
		return true
	default:
		return false
	}
}

// Defines values for TransportCreateInvitationRequestRole.
const (
	InviteGrantAdmin  TransportCreateInvitationRequestRole = "admin"
	InviteGrantMember TransportCreateInvitationRequestRole = "member"
	InviteGrantViewer TransportCreateInvitationRequestRole = "viewer"
)

// Valid indicates whether the value is a known member of the TransportCreateInvitationRequestRole enum.
func (e TransportCreateInvitationRequestRole) Valid() bool {
	switch e {
	case InviteGrantAdmin:
		return true
	case InviteGrantMember:
		return true
	case InviteGrantViewer:
		return true
	default:
		return false
	}
}

// Defines values for TransportHealthLiveResponseStatus.
const (
	Alive TransportHealthLiveResponseStatus = "alive"
)

// Valid indicates whether the value is a known member of the TransportHealthLiveResponseStatus enum.
func (e TransportHealthLiveResponseStatus) Valid() bool {
	switch e {
	case Alive:
		return true
	default:
		return false
	}
}

// Defines values for TransportHealthReadyResponseChecksState.
const (
	TransportHealthReadyResponseChecksStateNotReady TransportHealthReadyResponseChecksState = "not_ready"
	TransportHealthReadyResponseChecksStateReady    TransportHealthReadyResponseChecksState = "ready"
)

// Valid indicates whether the value is a known member of the TransportHealthReadyResponseChecksState enum.
func (e TransportHealthReadyResponseChecksState) Valid() bool {
	switch e {
	case TransportHealthReadyResponseChecksStateNotReady:
		return true
	case TransportHealthReadyResponseChecksStateReady:
		return true
	default:
		return false
	}
}

// Defines values for TransportHealthReadyResponseStatus.
const (
	TransportHealthReadyResponseStatusNotReady TransportHealthReadyResponseStatus = "not_ready"
	TransportHealthReadyResponseStatusReady    TransportHealthReadyResponseStatus = "ready"
)

// Valid indicates whether the value is a known member of the TransportHealthReadyResponseStatus enum.
func (e TransportHealthReadyResponseStatus) Valid() bool {
	switch e {
	case TransportHealthReadyResponseStatusNotReady:
		return true
	case TransportHealthReadyResponseStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for TransportIdentityErrorActionType.
const (
	Redirect TransportIdentityErrorActionType = "redirect"
)

// Valid indicates whether the value is a known member of the TransportIdentityErrorActionType enum.
func (e TransportIdentityErrorActionType) Valid() bool {
	switch e {
	case Redirect:
		return true
	default:
		return false
	}
}

// Defines values for TransportIdentityResponseAuthenticated.
const (
	True TransportIdentityResponseAuthenticated = true
)

// Valid indicates whether the value is a known member of the TransportIdentityResponseAuthenticated enum.
func (e TransportIdentityResponseAuthenticated) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// Defines values for TransportInvitationRole.
const (
	InviteAdmin  TransportInvitationRole = "admin"
	InviteMember TransportInvitationRole = "member"
	InviteViewer TransportInvitationRole = "viewer"
)

// Valid indicates whether the value is a known member of the TransportInvitationRole enum.
func (e TransportInvitationRole) Valid() bool {
	switch e {
	case InviteAdmin:
		return true
	case InviteMember:
		return true
	case InviteViewer:
		return true
	default:
		return false
	}
}

// Defines values for TransportInvitationStatus.
const (
	InviteAccepted TransportInvitationStatus = "Accepted"
	InviteExpired  TransportInvitationStatus = "Expired"
	InviteQueued   TransportInvitationStatus = "Queued"
	InviteRevoked  TransportInvitationStatus = "Revoked"
)

// Valid indicates whether the value is a known member of the TransportInvitationStatus enum.
func (e TransportInvitationStatus) Valid() bool {
	switch e {
	case InviteAccepted:
		return true
	case InviteExpired:
		return true
	case InviteQueued:
		return true
	case InviteRevoked:
		return true
	default:
		return false
	}
}

// Defines values for TransportLinkLifecycle.
const (
	TransportLinkLifecycleActive   TransportLinkLifecycle = "active"
	TransportLinkLifecycleArchived TransportLinkLifecycle = "archived"
	TransportLinkLifecycleDeleted  TransportLinkLifecycle = "deleted"
	TransportLinkLifecycleDisabled TransportLinkLifecycle = "disabled"
)

// Valid indicates whether the value is a known member of the TransportLinkLifecycle enum.
func (e TransportLinkLifecycle) Valid() bool {
	switch e {
	case TransportLinkLifecycleActive:
		return true
	case TransportLinkLifecycleArchived:
		return true
	case TransportLinkLifecycleDeleted:
		return true
	case TransportLinkLifecycleDisabled:
		return true
	default:
		return false
	}
}

// Defines values for TransportMemberResponseActorRole.
const (
	CapabilityAdmin  TransportMemberResponseActorRole = "admin"
	CapabilityMember TransportMemberResponseActorRole = "member"
	CapabilityOwner  TransportMemberResponseActorRole = "owner"
	CapabilityViewer TransportMemberResponseActorRole = "viewer"
)

// Valid indicates whether the value is a known member of the TransportMemberResponseActorRole enum.
func (e TransportMemberResponseActorRole) Valid() bool {
	switch e {
	case CapabilityAdmin:
		return true
	case CapabilityMember:
		return true
	case CapabilityOwner:
		return true
	case CapabilityViewer:
		return true
	default:
		return false
	}
}

// Defines values for TransportTeamMemberRole.
const (
	TeamAdmin  TransportTeamMemberRole = "admin"
	TeamMember TransportTeamMemberRole = "member"
	TeamOwner  TransportTeamMemberRole = "owner"
	TeamViewer TransportTeamMemberRole = "viewer"
)

// Valid indicates whether the value is a known member of the TransportTeamMemberRole enum.
func (e TransportTeamMemberRole) Valid() bool {
	switch e {
	case TeamAdmin:
		return true
	case TeamMember:
		return true
	case TeamOwner:
		return true
	case TeamViewer:
		return true
	default:
		return false
	}
}

// Defines values for TransportWorkspaceRole.
const (
	Admin  TransportWorkspaceRole = "admin"
	Member TransportWorkspaceRole = "member"
	Owner  TransportWorkspaceRole = "owner"
	Viewer TransportWorkspaceRole = "viewer"
)

// Valid indicates whether the value is a known member of the TransportWorkspaceRole enum.
func (e TransportWorkspaceRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Member:
		return true
	case Owner:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Defines values for ListLinksParamsState.
const (
	ListLinksParamsStateActive     ListLinksParamsState = "active"
	ListLinksParamsStateArchived   ListLinksParamsState = "archived"
	ListLinksParamsStateDeleted    ListLinksParamsState = "deleted"
	ListLinksParamsStateDisabled   ListLinksParamsState = "disabled"
	ListLinksParamsStateNondeleted ListLinksParamsState = "nondeleted"
)

// Valid indicates whether the value is a known member of the ListLinksParamsState enum.
func (e ListLinksParamsState) Valid() bool {
	switch e {
	case ListLinksParamsStateActive:
		return true
	case ListLinksParamsStateArchived:
		return true
	case ListLinksParamsStateDeleted:
		return true
	case ListLinksParamsStateDisabled:
		return true
	case ListLinksParamsStateNondeleted:
		return true
	default:
		return false
	}
}

// TransportChangeMemberRoleRequest defines model for transport.ChangeMemberRoleRequest.
type TransportChangeMemberRoleRequest struct {
	Role TransportChangeMemberRoleRequestRole `json:"role"`
}

// TransportChangeMemberRoleRequestRole defines model for TransportChangeMemberRoleRequest.Role.
type TransportChangeMemberRoleRequestRole string

// TransportCreateInvitationRequest Server trims and casefolds email, max 254 bytes, preserving dot/plus aliases; owner grants admin/member/viewer, admin grants member/viewer.
type TransportCreateInvitationRequest struct {
	Email string                               `json:"email"`
	Role  TransportCreateInvitationRequestRole `json:"role"`
}

// TransportCreateInvitationRequestRole defines model for TransportCreateInvitationRequest.Role.
type TransportCreateInvitationRequestRole string

// TransportCreateLinkRequest Public HTTP(S) destination, optional title of at most 200 Unicode characters and optional ASCII customKey, lowercased before validation and hashing. Keys use 3–64 letters, digits, underscores or hyphens and start with a letter or digit; system paths are reserved. Creation never fetches the destination.
type TransportCreateLinkRequest struct {
	CustomKey   *string `json:"customKey,omitempty"`
	Destination string  `json:"destination"`
	Title       *string `json:"title,omitempty"`
}

// TransportCreateWorkspaceRequest Explicit workspace name; the server trims Unicode whitespace and validates 1–100 Unicode characters.
type TransportCreateWorkspaceRequest struct {
	Name string `json:"name"`
}

// TransportHealthLiveResponse Process liveness, independent of external dependencies.
//
// Example: {"status":"alive"}
type TransportHealthLiveResponse struct {
	Status TransportHealthLiveResponseStatus `json:"status"`
}

// TransportHealthLiveResponseStatus defines model for TransportHealthLiveResponse.Status.
type TransportHealthLiveResponseStatus string

// TransportHealthReadyResponse Readiness of this process and its required components. Only coarse states are exposed.
//
// Example: {"checks":[{"name":"database","state":"ready"}],"status":"ready"}
type TransportHealthReadyResponse struct {
	Checks []struct {
		Name  string                                  `json:"name"`
		State TransportHealthReadyResponseChecksState `json:"state"`
	} `json:"checks"`
	Status TransportHealthReadyResponseStatus `json:"status"`
}

// TransportHealthReadyResponseChecksState defines model for TransportHealthReadyResponse.Checks.State.
type TransportHealthReadyResponseChecksState string

// TransportHealthReadyResponseStatus defines model for TransportHealthReadyResponse.Status.
type TransportHealthReadyResponseStatus string

// TransportIdentityError Safe authentication failure without token or provider diagnostics.
type TransportIdentityError struct {
	Action *struct {
		Message string                           `json:"message"`
		Type    TransportIdentityErrorActionType `json:"type"`
		Value   string                           `json:"value"`
	} `json:"action"`
	Code   string `json:"code"`
	Errors *[]struct {
		Error string `json:"error"`
		Field string `json:"field"`
	} `json:"errors"`
	Message  string `json:"message"`
	Override bool   `json:"override"`
	Status   int    `json:"status"`
}

// TransportIdentityErrorActionType defines model for TransportIdentityError.Action.Type.
type TransportIdentityErrorActionType string

// TransportIdentityResponse Committed internal UUID and verified primary email for an active bearer session. Provider identity is never merged by email.
type TransportIdentityResponse struct {
	Authenticated TransportIdentityResponseAuthenticated `json:"authenticated"`
	LastWorkspace *TransportWorkspace                    `json:"lastWorkspace"`
	User          struct {
		Email string `json:"email"`
		Id    string `json:"id"`
	} `json:"user"`
	Workspaces []TransportWorkspace `json:"workspaces"`
}

// TransportIdentityResponseAuthenticated defines model for TransportIdentityResponse.Authenticated.
type TransportIdentityResponseAuthenticated bool

// TransportInvitation defines model for transport.Invitation.
type TransportInvitation struct {
	Email       string                    `json:"email"`
	ExpiresAt   string                    `json:"expiresAt"`
	Id          string                    `json:"id"`
	Role        TransportInvitationRole   `json:"role"`
	Status      TransportInvitationStatus `json:"status"`
	WorkspaceId string                    `json:"workspaceId"`
}

// TransportInvitationRole defines model for TransportInvitation.Role.
type TransportInvitationRole string

// TransportInvitationStatus defines model for TransportInvitation.Status.
type TransportInvitationStatus string

// TransportInvitationResponse defines model for transport.InvitationResponse.
type TransportInvitationResponse struct {
	Invitation TransportInvitation `json:"invitation"`
}

// TransportInvitationsResponse defines model for transport.InvitationsResponse.
type TransportInvitationsResponse struct {
	Items     []TransportInvitation `json:"items"`
	NextAfter *string               `json:"nextAfter"`
}

// TransportLink defines model for transport.Link.
type TransportLink struct {
	CreatedAt string `json:"createdAt"`
	Creator   struct {
		Email string `json:"email"`
		Id    string `json:"id"`
	} `json:"creator"`
	Destination string                   `json:"destination"`
	Id          string                   `json:"id"`
	Lifecycle   TransportLinkLifecycle   `json:"lifecycle"`
	ShortUrl    string                   `json:"shortUrl"`
	Suspension  *TransportLinkSuspension `json:"suspension"`
	Title       string                   `json:"title"`
	UpdatedAt   string                   `json:"updatedAt"`
	Version     string                   `json:"version"`
	WorkspaceId string                   `json:"workspaceId"`
}

// TransportLinkLifecycle defines model for TransportLink.Lifecycle.
type TransportLinkLifecycle string

// TransportLinkResponse defines model for transport.LinkResponse.
type TransportLinkResponse struct {
	Link TransportLink `json:"link"`
}

// TransportLinkSuspension defines model for transport.LinkSuspension.
type TransportLinkSuspension struct {
	ActorId string `json:"actorId"`
	At      string `json:"at"`
	Reason  string `json:"reason"`
}

// TransportLinksResponse defines model for transport.LinksResponse.
type TransportLinksResponse struct {
	Items []TransportLink `json:"items"`

	// NextCursor Opaque signed workspace/query-bound continuation; null means authoritative exhaustion.
	NextCursor *string `json:"nextCursor"`
}

// TransportMemberRemovalResponse defines model for transport.MemberRemovalResponse.
type TransportMemberRemovalResponse struct {
	RemovedUserId string `json:"removedUserId"`
	SelfRemoved   bool   `json:"selfRemoved"`
	WorkspaceId   string `json:"workspaceId"`
}

// TransportMemberResponse defines model for transport.MemberResponse.
type TransportMemberResponse struct {
	ActorRole TransportMemberResponseActorRole `json:"actorRole"`
	Member    TransportTeamMember              `json:"member"`
}

// TransportMemberResponseActorRole defines model for TransportMemberResponse.ActorRole.
type TransportMemberResponseActorRole string

// TransportMembersResponse defines model for transport.MembersResponse.
type TransportMembersResponse struct {
	Items []TransportTeamMember `json:"items"`

	// NextAfter Last user UUID continuation; null means authoritative exhaustion. Never grants workspace authority.
	NextAfter *string `json:"nextAfter"`
}

// TransportRemoveMemberRequest defines model for transport.RemoveMemberRequest.
type TransportRemoveMemberRequest = map[string]interface{}

// TransportTeamMember defines model for transport.TeamMember.
type TransportTeamMember struct {
	Email       string                  `json:"email"`
	Id          string                  `json:"id"`
	Role        TransportTeamMemberRole `json:"role"`
	WorkspaceId string                  `json:"workspaceId"`
}

// TransportTeamMemberRole defines model for TransportTeamMember.Role.
type TransportTeamMemberRole string

// TransportWorkspace defines model for transport.Workspace.
type TransportWorkspace struct {
	Id   string                 `json:"id"`
	Name string                 `json:"name"`
	Role TransportWorkspaceRole `json:"role"`
}

// TransportWorkspaceRole defines model for TransportWorkspace.Role.
type TransportWorkspaceRole string

// TransportWorkspacePreferenceRequest Selection must be reauthorized against current Flux membership.
type TransportWorkspacePreferenceRequest struct {
	WorkspaceId string `json:"workspaceId"`
}

// TransportWorkspaceResponse defines model for transport.WorkspaceResponse.
type TransportWorkspaceResponse struct {
	ManagedHost *string            `json:"managedHost,omitempty"`
	Workspace   TransportWorkspace `json:"workspace"`
}

// TransportWorkspacesResponse defines model for transport.WorkspacesResponse.
type TransportWorkspacesResponse struct {
	Workspaces []TransportWorkspace `json:"workspaces"`
}

// HealthLiveResponse is the canonical liveness transport in this package.
type HealthLiveResponse = TransportHealthLiveResponse

// HealthReadyResponse is the canonical readiness transport in this package.
type HealthReadyResponse = TransportHealthReadyResponse

// CreateWorkspaceParams defines parameters for CreateWorkspace.
type CreateWorkspaceParams struct {
	IdempotencyKey string `json:"idempotency-key"`
}

// ListInvitationsParams defines parameters for ListInvitations.
type ListInvitationsParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
}

// CreateInvitationParams defines parameters for CreateInvitation.
type CreateInvitationParams struct {
	IdempotencyKey string `json:"idempotency-key"`
}

// ListLinksParams defines parameters for ListLinks.
type ListLinksParams struct {
	Limit  *string `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Search Literal case-insensitive substring across short key, title or destination; surrounding Unicode whitespace is trimmed. Maximum 200 Unicode characters.
	Search *string               `form:"search,omitempty" json:"search,omitempty"`
	State  *ListLinksParamsState `form:"state,omitempty" json:"state,omitempty"`
}

// ListLinksParamsState defines parameters for ListLinks.
type ListLinksParamsState string

// CreateLinkParams defines parameters for CreateLink.
type CreateLinkParams struct {
	IdempotencyKey string `json:"idempotency-key"`
}

// ListMembersParams defines parameters for ListMembers.
type ListMembersParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
}

// RemoveMemberParams defines parameters for RemoveMember.
type RemoveMemberParams struct {
	IdempotencyKey string `json:"idempotency-key"`
}

// ChangeMemberRoleParams defines parameters for ChangeMemberRole.
type ChangeMemberRoleParams struct {
	IdempotencyKey string `json:"idempotency-key"`
}

// SelectWorkspaceJSONRequestBody defines body for SelectWorkspace for application/json ContentType.
type SelectWorkspaceJSONRequestBody = TransportWorkspacePreferenceRequest

// CreateWorkspaceJSONRequestBody defines body for CreateWorkspace for application/json ContentType.
type CreateWorkspaceJSONRequestBody = TransportCreateWorkspaceRequest

// CreateInvitationJSONRequestBody defines body for CreateInvitation for application/json ContentType.
type CreateInvitationJSONRequestBody = TransportCreateInvitationRequest

// CreateLinkJSONRequestBody defines body for CreateLink for application/json ContentType.
type CreateLinkJSONRequestBody = TransportCreateLinkRequest

// RemoveMemberJSONRequestBody defines body for RemoveMember for application/json ContentType.
type RemoveMemberJSONRequestBody = TransportRemoveMemberRequest

// ChangeMemberRoleJSONRequestBody defines body for ChangeMemberRole for application/json ContentType.
type ChangeMemberRoleJSONRequestBody = TransportChangeMemberRoleRequest
