// Package transport provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package transport

// Defines values for TransportHealthLiveResponseStatus.
const (
	Alive TransportHealthLiveResponseStatus = "alive"
)

// Valid indicates whether the value is a known member of the TransportHealthLiveResponseStatus enum.
func (e TransportHealthLiveResponseStatus) Valid() bool {
	switch e {
	case Alive:
		return true
	default:
		return false
	}
}

// Defines values for TransportHealthReadyResponseChecksState.
const (
	TransportHealthReadyResponseChecksStateNotReady TransportHealthReadyResponseChecksState = "not_ready"
	TransportHealthReadyResponseChecksStateReady    TransportHealthReadyResponseChecksState = "ready"
)

// Valid indicates whether the value is a known member of the TransportHealthReadyResponseChecksState enum.
func (e TransportHealthReadyResponseChecksState) Valid() bool {
	switch e {
	case TransportHealthReadyResponseChecksStateNotReady:
		return true
	case TransportHealthReadyResponseChecksStateReady:
		return true
	default:
		return false
	}
}

// Defines values for TransportHealthReadyResponseStatus.
const (
	TransportHealthReadyResponseStatusNotReady TransportHealthReadyResponseStatus = "not_ready"
	TransportHealthReadyResponseStatusReady    TransportHealthReadyResponseStatus = "ready"
)

// Valid indicates whether the value is a known member of the TransportHealthReadyResponseStatus enum.
func (e TransportHealthReadyResponseStatus) Valid() bool {
	switch e {
	case TransportHealthReadyResponseStatusNotReady:
		return true
	case TransportHealthReadyResponseStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for TransportIdentityErrorActionType.
const (
	Redirect TransportIdentityErrorActionType = "redirect"
)

// Valid indicates whether the value is a known member of the TransportIdentityErrorActionType enum.
func (e TransportIdentityErrorActionType) Valid() bool {
	switch e {
	case Redirect:
		return true
	default:
		return false
	}
}

// Defines values for TransportIdentityResponseAuthenticated.
const (
	True TransportIdentityResponseAuthenticated = true
)

// Valid indicates whether the value is a known member of the TransportIdentityResponseAuthenticated enum.
func (e TransportIdentityResponseAuthenticated) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// Defines values for TransportLinkLifecycle.
const (
	Active   TransportLinkLifecycle = "active"
	Archived TransportLinkLifecycle = "archived"
	Deleted  TransportLinkLifecycle = "deleted"
	Disabled TransportLinkLifecycle = "disabled"
)

// Valid indicates whether the value is a known member of the TransportLinkLifecycle enum.
func (e TransportLinkLifecycle) Valid() bool {
	switch e {
	case Active:
		return true
	case Archived:
		return true
	case Deleted:
		return true
	case Disabled:
		return true
	default:
		return false
	}
}

// Defines values for TransportWorkspaceRole.
const (
	Admin  TransportWorkspaceRole = "admin"
	Member TransportWorkspaceRole = "member"
	Owner  TransportWorkspaceRole = "owner"
	Viewer TransportWorkspaceRole = "viewer"
)

// Valid indicates whether the value is a known member of the TransportWorkspaceRole enum.
func (e TransportWorkspaceRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Member:
		return true
	case Owner:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// TransportCreateLinkRequest Public HTTP(S) destination, optional title of at most 200 Unicode characters and optional ASCII customKey, lowercased before validation and hashing. Keys use 3–64 letters, digits, underscores or hyphens and start with a letter or digit; system paths are reserved. Creation never fetches the destination.
type TransportCreateLinkRequest struct {
	CustomKey   *string `json:"customKey,omitempty"`
	Destination string  `json:"destination"`
	Title       *string `json:"title,omitempty"`
}

// TransportCreateWorkspaceRequest Explicit workspace name; the server trims Unicode whitespace and validates 1–100 Unicode characters.
type TransportCreateWorkspaceRequest struct {
	Name string `json:"name"`
}

// TransportHealthLiveResponse Process liveness, independent of external dependencies.
//
// Example: {"status":"alive"}
type TransportHealthLiveResponse struct {
	Status TransportHealthLiveResponseStatus `json:"status"`
}

// TransportHealthLiveResponseStatus defines model for TransportHealthLiveResponse.Status.
type TransportHealthLiveResponseStatus string

// TransportHealthReadyResponse Readiness of this process and its required components. Only coarse states are exposed.
//
// Example: {"checks":[{"name":"database","state":"ready"}],"status":"ready"}
type TransportHealthReadyResponse struct {
	Checks []struct {
		Name  string                                  `json:"name"`
		State TransportHealthReadyResponseChecksState `json:"state"`
	} `json:"checks"`
	Status TransportHealthReadyResponseStatus `json:"status"`
}

// TransportHealthReadyResponseChecksState defines model for TransportHealthReadyResponse.Checks.State.
type TransportHealthReadyResponseChecksState string

// TransportHealthReadyResponseStatus defines model for TransportHealthReadyResponse.Status.
type TransportHealthReadyResponseStatus string

// TransportIdentityError Safe authentication failure without token or provider diagnostics.
type TransportIdentityError struct {
	Action *struct {
		Message string                           `json:"message"`
		Type    TransportIdentityErrorActionType `json:"type"`
		Value   string                           `json:"value"`
	} `json:"action"`
	Code   string `json:"code"`
	Errors *[]struct {
		Error string `json:"error"`
		Field string `json:"field"`
	} `json:"errors"`
	Message  string `json:"message"`
	Override bool   `json:"override"`
	Status   int    `json:"status"`
}

// TransportIdentityErrorActionType defines model for TransportIdentityError.Action.Type.
type TransportIdentityErrorActionType string

// TransportIdentityResponse Committed internal UUID and verified primary email for an active bearer session. Provider identity is never merged by email.
type TransportIdentityResponse struct {
	Authenticated TransportIdentityResponseAuthenticated `json:"authenticated"`
	LastWorkspace *TransportWorkspace                    `json:"lastWorkspace"`
	User          struct {
		Email string `json:"email"`
		Id    string `json:"id"`
	} `json:"user"`
	Workspaces []TransportWorkspace `json:"workspaces"`
}

// TransportIdentityResponseAuthenticated defines model for TransportIdentityResponse.Authenticated.
type TransportIdentityResponseAuthenticated bool

// TransportLink defines model for transport.Link.
type TransportLink struct {
	CreatedAt string `json:"createdAt"`
	Creator   struct {
		Email string `json:"email"`
		Id    string `json:"id"`
	} `json:"creator"`
	Destination string                   `json:"destination"`
	Id          string                   `json:"id"`
	Lifecycle   TransportLinkLifecycle   `json:"lifecycle"`
	ShortUrl    string                   `json:"shortUrl"`
	Suspension  *TransportLinkSuspension `json:"suspension"`
	Title       string                   `json:"title"`
	UpdatedAt   string                   `json:"updatedAt"`
	Version     string                   `json:"version"`
	WorkspaceId string                   `json:"workspaceId"`
}

// TransportLinkLifecycle defines model for TransportLink.Lifecycle.
type TransportLinkLifecycle string

// TransportLinkResponse defines model for transport.LinkResponse.
type TransportLinkResponse struct {
	Link TransportLink `json:"link"`
}

// TransportLinkSuspension defines model for transport.LinkSuspension.
type TransportLinkSuspension struct {
	ActorId string `json:"actorId"`
	At      string `json:"at"`
	Reason  string `json:"reason"`
}

// TransportLinksResponse defines model for transport.LinksResponse.
type TransportLinksResponse struct {
	Items []TransportLink `json:"items"`

	// NextCursor Opaque signed workspace/query-bound continuation; null means authoritative exhaustion.
	NextCursor *string `json:"nextCursor"`
}

// TransportWorkspace defines model for transport.Workspace.
type TransportWorkspace struct {
	Id   string                 `json:"id"`
	Name string                 `json:"name"`
	Role TransportWorkspaceRole `json:"role"`
}

// TransportWorkspaceRole defines model for TransportWorkspace.Role.
type TransportWorkspaceRole string

// TransportWorkspacePreferenceRequest Selection must be reauthorized against current Flux membership.
type TransportWorkspacePreferenceRequest struct {
	WorkspaceId string `json:"workspaceId"`
}

// TransportWorkspaceResponse defines model for transport.WorkspaceResponse.
type TransportWorkspaceResponse struct {
	ManagedHost *string            `json:"managedHost,omitempty"`
	Workspace   TransportWorkspace `json:"workspace"`
}

// TransportWorkspacesResponse defines model for transport.WorkspacesResponse.
type TransportWorkspacesResponse struct {
	Workspaces []TransportWorkspace `json:"workspaces"`
}

// HealthLiveResponse is the canonical liveness transport in this package.
type HealthLiveResponse = TransportHealthLiveResponse

// HealthReadyResponse is the canonical readiness transport in this package.
type HealthReadyResponse = TransportHealthReadyResponse

// CreateWorkspaceParams defines parameters for CreateWorkspace.
type CreateWorkspaceParams struct {
	IdempotencyKey string `json:"idempotency-key"`
}

// ListLinksParams defines parameters for ListLinks.
type ListLinksParams struct {
	Limit  *string `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateLinkParams defines parameters for CreateLink.
type CreateLinkParams struct {
	IdempotencyKey string `json:"idempotency-key"`
}

// SelectWorkspaceJSONRequestBody defines body for SelectWorkspace for application/json ContentType.
type SelectWorkspaceJSONRequestBody = TransportWorkspacePreferenceRequest

// CreateWorkspaceJSONRequestBody defines body for CreateWorkspace for application/json ContentType.
type CreateWorkspaceJSONRequestBody = TransportCreateWorkspaceRequest

// CreateLinkJSONRequestBody defines body for CreateLink for application/json ContentType.
type CreateLinkJSONRequestBody = TransportCreateLinkRequest
