package qr_test

import (
	"bytes"
	"image/png"
	"strings"
	"testing"

	"flux/apps/backend/internal/modules/qr"
)

func TestQRGenerator_GeneratePNG(t *testing.T) {
	gen := qr.NewQRGenerator()

	opts := qr.QROptions{
		Size:            256,
		Format:          "png",
		ErrorCorrection: "H",
	}

	data, err := gen.GeneratePNG("https://flux.dev/openai", opts)
	if err != nil {
		t.Fatalf("expected no error generating PNG, got: %v", err)
	}

	if len(data) == 0 {
		t.Fatalf("expected non-empty byte slice for PNG output")
	}

	// Verify header is a valid PNG image
	img, err := png.Decode(bytes.NewReader(data))
	if err != nil {
		t.Fatalf("failed to decode generated PNG bytes: %v", err)
	}

	bounds := img.Bounds()
	if bounds.Dx() != 256 || bounds.Dy() != 256 {
		t.Errorf("expected PNG dimensions 256x256, got %dx%d", bounds.Dx(), bounds.Dy())
	}
}

func TestQRGenerator_GenerateSVG(t *testing.T) {
	gen := qr.NewQRGenerator()

	opts := qr.QROptions{
		Size:            256,
		Format:          "svg",
		ErrorCorrection: "M",
	}

	svgContent, err := gen.GenerateSVG("https://flux.dev/openai", opts)
	if err != nil {
		t.Fatalf("expected no error generating SVG, got: %v", err)
	}

	if !strings.Contains(svgContent, "<svg") || !strings.Contains(svgContent, "</svg>") {
		t.Errorf("expected valid SVG XML markup, got: %s", svgContent)
	}
}

func TestQRService_Caching(t *testing.T) {
	cache := qr.NewMockQRCache()
	svc := qr.NewQRService(cache)

	opts := qr.QROptions{
		Size:            512,
		Format:          "png",
		ErrorCorrection: "Q",
	}

	// First call generates and populates cache
	data1, err := svc.Generate("https://flux.dev/testlink", opts)
	if err != nil {
		t.Fatalf("expected no error on first call: %v", err)
	}

	// Second call should return cached bytes directly
	data2, err := svc.Generate("https://flux.dev/testlink", opts)
	if err != nil {
		t.Fatalf("expected no error on cached call: %v", err)
	}

	if !bytes.Equal(data1, data2) {
		t.Errorf("expected cached QR bytes to match freshly generated bytes")
	}
}
