import {
  ZChangeMemberRoleRequest,
  ZCreateInvitationRequest,
  ZCreateLinkRequest,
  ZCreateWorkspaceRequest,
  ZIdentityError,
  ZIdentityResponse,
  ZInvitationResponse,
  ZInvitationsResponse,
  ZLinkListQuery,
  ZLinkResponse,
  ZLinksResponse,
  ZMemberListQuery,
  ZMemberRemovalResponse,
  ZMemberResponse,
  ZMembersResponse,
  ZRemoveMemberRequest,
  ZWorkspacePreferenceRequest,
  ZWorkspaceResponse,
  ZWorkspacesResponse,
} from "@flux/zod";
import { initContract } from "@ts-rest/core";
import { z } from "zod";
import { getSecurityMetadata } from "../utils.js";

const c = initContract();

export const identityContract = c.router({
  createInvitation: {
    summary: "Queue a tenant invitation with encrypted durable delivery intent",
    description:
      "Current SQL owner/admin authority is locked workspace then actor before replay hashes. Owners grant admin/member/viewer; admins grant member/viewer. Email trims and casefolds without dot/plus rewriting, maximum 254 bytes. Pending workspace/email uniqueness returns 409 INVITATION_PENDING. Elapsed pending records expire transactionally before the partial uniqueness check. Seven-day expiry. Atomic invitation, AES-256-GCM encrypted delivery envelope bound to workspace/invitation/delivery/key identity, SHA-256 digest of a 256-bit random token, protected durable actor audit and workspace/actor/invitation.create/key 24-hour ledger. Replay requires current authorization; changed content conflicts. Queued is truthful until independent worker acknowledgement. API performs no email delivery or consumer work. Responses never expose token, digest, key ID or ciphertext. Unknown fields, nulls, trailing JSON and query parameters fail closed. No-store; existing Origin/JSON/64 KiB limits and rate-limit metadata apply.",
    path: "/api/v1/workspaces/:workspaceId/invitations",
    method: "POST",
    metadata: getSecurityMetadata(),
    pathParams: z.object({ workspaceId: z.string().uuid() }),
    headers: z.object({ "idempotency-key": z.string().regex(/^[A-Za-z0-9_-]{16,128}$/) }),
    body: ZCreateInvitationRequest,
    responses: {
      201: ZInvitationResponse,
      400: ZIdentityError,
      401: ZIdentityError,
      403: ZIdentityError,
      404: ZIdentityError,
      409: ZIdentityError,
      413: ZIdentityError,
      415: ZIdentityError,
      429: ZIdentityError,
      503: ZIdentityError,
    },
  },
  listInvitations: {
    summary: "List freshly authorized workspace invitations",
    description:
      "Current SQL owner/admin Team capability required for every page, in workspace-first transaction. Fixed 25-row UUID seek page plus one lookahead, honest nextAfter or null, no totals. Exposes only scoped UUID, email, role, Queued/Expired/Accepted/Revoked status and expiry. API never claims delivered; independent worker is a later slice. No raw delivery material in response or logs. Foreign/missing/removed access returns safe 404, member/viewer 403. No-store with rate-limit metadata.",
    path: "/api/v1/workspaces/:workspaceId/invitations",
    method: "GET",
    metadata: getSecurityMetadata(),
    pathParams: z.object({ workspaceId: z.string().uuid() }),
    query: ZMemberListQuery,
    responses: {
      200: ZInvitationsResponse,
      400: ZIdentityError,
      401: ZIdentityError,
      403: ZIdentityError,
      404: ZIdentityError,
      429: ZIdentityError,
      503: ZIdentityError,
    },
  },
  removeMember: {
    summary: "Remove a current workspace member while retaining durable creator provenance",
    description:
      "Requires exact allowed Origin, empty JSON object and Idempotency-Key. Locks workspace exclusively, then current actor membership, then scoped target membership. Owners may remove all roles; admins may remove member/viewer only. Final owner removal returns 409 OWNER_REQUIRED: Promote another owner first. Current SQL actor authority precedes all ledger access; current target policy or the protected committed target-role snapshot precedes hash comparison. A committed same-target retry may replay after physical membership removal for a still-authorized actor. Changed target returns 409 IDEMPOTENCY_CONFLICT; a new request for a missing target returns 404. Former actors cannot replay. SHA-256 canonical user UUID and workspace/actor/member.remove/key ledger scope retain results at least 24 hours. Membership deletion, immutable protected durable actor/action/target snapshot/time audit, and ledger commit atomically. Active/deleted links, reserved keys, creator users and audit actor provenance never cascade. All subsequent removed-actor reads, writes and replay are denied. Self removal reports selfRemoved for immediate scoped content disposal; it does not sign out the session. No-store; 429 includes Retry-After and rate-limit metadata.",
    path: "/api/v1/workspaces/:workspaceId/members/:memberId",
    method: "DELETE",
    metadata: getSecurityMetadata(),
    pathParams: z.object({ workspaceId: z.string().uuid(), memberId: z.string().uuid() }),
    headers: z.object({ "idempotency-key": z.string().regex(/^[A-Za-z0-9_-]{16,128}$/) }),
    body: ZRemoveMemberRequest,
    responses: {
      200: ZMemberRemovalResponse,
      400: ZIdentityError,
      401: ZIdentityError,
      403: ZIdentityError,
      404: ZIdentityError,
      409: ZIdentityError,
      413: ZIdentityError,
      415: ZIdentityError,
      429: ZIdentityError,
      503: ZIdentityError,
    },
  },
  changeMemberRole: {
    summary: "Change a current workspace member's role",
    description:
      "Requires exact allowed Origin, JSON and Idempotency-Key. Locks workspace exclusively, then actor membership, then scoped target membership. Current PostgreSQL owners manage all roles; admins may target and grant member/viewer only, never admin/owner/self escalation. Provider claims never authorize. Last owner demotion returns 409 OWNER_REQUIRED: Promote another owner first. Ownership transfer explicitly promotes an existing member before demotion. Fresh actor and target authorization precedes hash/replay reads. SHA-256 canonical target/role hash and workspace/actor/member.role/key scope retain committed responses at least 24 hours. Identical authorized retries return the original result with one audit; changed payload returns 409 IDEMPOTENCY_CONFLICT. Role effect, immutable protected durable actor/action/target membership snapshot/time audit, and ledger commit atomically. Foreign or removed access returns safe 404. Unknown fields, nulls and invalid roles fail closed. No-store. 429 includes Retry-After and rate-limit metadata.",
    path: "/api/v1/workspaces/:workspaceId/members/:memberId",
    method: "PATCH",
    metadata: getSecurityMetadata(),
    pathParams: z.object({ workspaceId: z.string().uuid(), memberId: z.string().uuid() }),
    headers: z.object({ "idempotency-key": z.string().regex(/^[A-Za-z0-9_-]{16,128}$/) }),
    body: ZChangeMemberRoleRequest,
    responses: {
      200: ZMemberResponse,
      400: ZIdentityError,
      401: ZIdentityError,
      403: ZIdentityError,
      404: ZIdentityError,
      409: ZIdentityError,
      413: ZIdentityError,
      415: ZIdentityError,
      429: ZIdentityError,
      503: ZIdentityError,
    },
  },
  listMembers: {
    summary: "Inspect freshly authorized workspace members",
    description:
      "Only current PostgreSQL owner/admin memberships grant Team access; provider organization claims never authorize. Workspace-first exclusive lock protects capability and member query in one transaction. Fixed 25-row pages ordered by durable user UUID, plus one lookahead. Optional after UUID is only a seek position; every page rechecks current membership. Unknown/duplicate/invalid query fields return 400; current members/viewers receive 403; foreign, missing or removed membership receives safe 404. Only durable user ID, verified email, workspace ID and current closed role are projected. No provider identifiers or history. At most 25 bounded 320-character emails keep success below the existing 64 KiB body budget. No totals. 429 includes Retry-After and rate-limit metadata. All responses are no-store.",
    path: "/api/v1/workspaces/:workspaceId/members",
    method: "GET",
    metadata: getSecurityMetadata(),
    pathParams: z.object({ workspaceId: z.string().uuid() }),
    query: ZMemberListQuery,
    responses: {
      200: ZMembersResponse,
      400: ZIdentityError,
      401: ZIdentityError,
      403: ZIdentityError,
      404: ZIdentityError,
      429: ZIdentityError,
      503: ZIdentityError,
    },
  },
  listLinks: {
    summary: "List a freshly authorized newest-first link library",
    description:
      "All current Flux members, including viewers, may search and filter scoped links. Default state is nondeleted; closed states are nondeleted, active, disabled, archived and deleted. Search is a literal case-insensitive substring of short key, title or destination, with SQL wildcards escaped and a maximum of 200 Unicode characters. Surrounding Unicode whitespace is trimmed before exact query fingerprinting. Defaults to 25 items, maximum 100, ordered createdAt descending then UUID descending. Fresh SQL workspace membership and tenant predicates are mandatory. Signed version-1 opaque cursors bind workspace, effective filter fingerprint, timestamp and UUID with HMAC-SHA256; they never grant membership. Fetches limit plus one and emits nextCursor only when an extra row exists. Malformed, oversized, tampered, foreign or mismatched cursors return 400 CURSOR_INVALID: This page is no longer available. Return to the first page. Changed normalized search or lifecycle rejects an existing cursor with CURSOR_INVALID. Duplicate, invalid or unknown query fields return 400. 429 responses include Retry-After and rate-limit metadata. No totals. All responses are no-store.",
    path: "/api/v1/workspaces/:workspaceId/links",
    method: "GET",
    metadata: getSecurityMetadata(),
    pathParams: z.object({ workspaceId: z.string().uuid() }),
    query: ZLinkListQuery,
    responses: {
      200: ZLinksResponse,
      400: ZIdentityError,
      401: ZIdentityError,
      404: ZIdentityError,
      429: ZIdentityError,
      503: ZIdentityError,
    },
  },
  createLink: {
    summary: "Create a safe generated or custom-key managed-domain link",
    description:
      "Requires allowed Origin, JSON and Idempotency-Key. Fresh write membership is checked under workspace shared lock before actor-scoped create replay. SHA-256 canonical payload and committed response share a 24-hour ledger and atomic transaction. Twelve cryptographic random bytes yield lowercase unpadded base32 keys, with at most five retries only on the named global host/key constraint, including deleted rows. Optional ASCII customKey is lowercased and validated as 3–64 characters with system paths reserved; global collisions return KEY_UNAVAILABLE without owner data and changed canonical payload returns REQUEST_REUSE_CONFLICT. Public HTTP(S) destinations only; no fetch or preview. All responses are no-store.",
    path: "/api/v1/workspaces/:workspaceId/links",
    method: "POST",
    metadata: getSecurityMetadata(),
    pathParams: z.object({ workspaceId: z.string().uuid() }),
    headers: z.object({ "idempotency-key": z.string().regex(/^[A-Za-z0-9_-]{16,128}$/) }),
    body: ZCreateLinkRequest,
    responses: {
      201: ZLinkResponse,
      400: ZIdentityError,
      401: ZIdentityError,
      403: ZIdentityError,
      404: ZIdentityError,
      409: ZIdentityError,
      413: ZIdentityError,
      415: ZIdentityError,
      429: ZIdentityError,
      503: ZIdentityError,
    },
  },
  getLink: {
    summary: "Inspect a freshly authorized scoped link",
    description:
      "All current Flux members may read. Foreign, missing and removed access returns safe 404. Durable creator identity remains after membership removal. No-store; lifecycle does not prove redirect availability.",
    path: "/api/v1/workspaces/:workspaceId/links/:linkId",
    method: "GET",
    metadata: getSecurityMetadata(),
    pathParams: z.object({ workspaceId: z.string().uuid(), linkId: z.string().uuid() }),
    responses: {
      200: ZLinkResponse,
      401: ZIdentityError,
      404: ZIdentityError,
      429: ZIdentityError,
      503: ZIdentityError,
    },
  },
  selectWorkspace: {
    summary: "Select a currently authorized workspace",
    description:
      "Requires exact allowed Origin and JSON. Locks the workspace and rechecks Flux membership before committing the identity-owned preference. All roles may select. Unknown, foreign and removed memberships return the same 404. The preference never authorizes subsequent access. All responses use Cache-Control: no-store.",
    path: "/api/v1/me/last-workspace",
    method: "PUT",
    metadata: getSecurityMetadata(),
    body: ZWorkspacePreferenceRequest,
    responses: {
      200: ZWorkspaceResponse,
      400: ZIdentityError,
      401: ZIdentityError,
      403: ZIdentityError,
      404: ZIdentityError,
      413: ZIdentityError,
      415: ZIdentityError,
      429: ZIdentityError,
      503: ZIdentityError,
    },
  },
  createWorkspace: {
    summary: "Create a named workspace and owner atomically",
    description:
      "Requires exact allowed Origin, JSON and Idempotency-Key. Canonical trimmed Unicode name is hashed with SHA-256; identity-scoped retries replay the committed workspace after fresh membership authorization, conflicting content returns 409. Ledger retention is at least 24 hours. All responses are no-store.",
    path: "/api/v1/workspaces",
    method: "POST",
    metadata: getSecurityMetadata(),
    headers: z.object({ "idempotency-key": z.string().regex(/^[A-Za-z0-9_-]{16,128}$/) }),
    body: ZCreateWorkspaceRequest,
    responses: {
      201: ZWorkspaceResponse,
      400: ZIdentityError,
      401: ZIdentityError,
      403: ZIdentityError,
      404: ZIdentityError,
      409: ZIdentityError,
      413: ZIdentityError,
      415: ZIdentityError,
      429: ZIdentityError,
      503: ZIdentityError,
    },
  },
  listWorkspaces: {
    summary: "List current workspace memberships",
    path: "/api/v1/workspaces",
    method: "GET",
    metadata: getSecurityMetadata(),
    responses: {
      200: ZWorkspacesResponse,
      401: ZIdentityError,
      429: ZIdentityError,
      503: ZIdentityError,
    },
  },
  getWorkspace: {
    summary: "Read a freshly authorized workspace summary",
    description:
      "Workspace and durable actor scope are required; foreign, unknown or removed memberships return the same 404. Provider organization claims confer no authority. All responses are no-store.",
    path: "/api/v1/workspaces/:workspaceId",
    method: "GET",
    metadata: getSecurityMetadata(),
    pathParams: z.object({ workspaceId: z.string().uuid() }),
    responses: {
      200: ZWorkspaceResponse,
      401: ZIdentityError,
      404: ZIdentityError,
      429: ZIdentityError,
      503: ZIdentityError,
    },
  },
  getMe: {
    summary: "Resolve the current internal user",
    description:
      "Requires an explicit bearer, exact issuer and authorized party, and a currently active provider session. First mapping verifies the provider primary email and commits a unique issuer/subject UUID in PostgreSQL; email never merges identities. Returns current Flux memberships and lastWorkspace only when authorized in the same membership snapshot, otherwise null without former workspace identifiers or names. All responses use Cache-Control: no-store. Cookies and provider organization claims grant no access.",
    path: "/api/v1/me",
    method: "GET",
    metadata: getSecurityMetadata(),
    responses: {
      200: ZIdentityResponse,
      401: ZIdentityError,
      429: ZIdentityError,
      503: ZIdentityError,
    },
  },
});
