import { test } from "node:test";
import assert from "node:assert/strict";
import { chmod, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const artifacts = [
  "packages/openapi/openapi.json",
  "apps/backend/static/openapi.json",
  "apps/backend/internal/transport/health.gen.go",
  "apps/backend/templates/emails/welcome.html",
];
const repository = fileURLToPath(new URL("../", import.meta.url));
type Generate = (options: {
  root: string;
  check: boolean;
  temporaryParent: string;
  generateArtifacts: (output: string, root: string) => Promise<void>;
}) => Promise<void>;

const load = async (): Promise<Generate> => {
  const module = await import("./generate.ts");
  assert.equal(typeof module.generate, "function");
  assert.deepEqual(module.artifactManifest, artifacts);
  return module.generate;
};

const put = async (root: string, path: string, bytes: string) => {
  await mkdir(dirname(join(root, path)), { recursive: true });
  await writeFile(join(root, path), bytes);
};
const expected = (path: string) => `generated:${path}\n`;
const regenerate = async (output: string) => {
  for (const path of artifacts) await put(output, path, expected(path));
};
const fixture = async (run: (root: string, temporaryParent: string) => Promise<void>) => {
  const parent = await mkdtemp(join(tmpdir(), "flux-generation-test-"));
  const root = join(parent, "repository");
  const temporaryParent = join(parent, "stages");
  await mkdir(temporaryParent);
  await put(root, "packages/zod/src/health.ts", "authored-source-sentinel");
  await regenerate(root);
  try {
    await run(root, temporaryParent);
    assert.deepEqual(await readdir(temporaryParent), [], "stages cleaned on success and failure");
    assert.equal(await readFile(join(root, "packages/zod/src/health.ts"), "utf8"), "authored-source-sentinel");
  } finally {
    await rm(parent, { recursive: true, force: true });
  }
};

test("matching generated bytes pass independently of Git and leave outputs unchanged", async () => {
  const generate = await load();
  await fixture(async (root, temporaryParent) => {
    await generate({ root, temporaryParent, check: true, generateArtifacts: regenerate });
    for (const path of artifacts) assert.equal(await readFile(join(root, path), "utf8"), expected(path));
  });
});

for (const path of artifacts) {
  for (const mutation of ["changed", "missing"]) {
    test(`${mutation} ${path} fails without repairing checked files or disclosing bytes`, async () => {
      const generate = await load();
      await fixture(async (root, temporaryParent) => {
        if (mutation === "missing") await rm(join(root, path));
        else await put(root, path, "private-artifact-sentinel");
        await assert.rejects(generate({ root, temporaryParent, check: true, generateArtifacts: regenerate }), (error: Error) => {
          assert.ok(error.message.includes(path));
          assert.ok(!error.message.includes("private-artifact-sentinel"));
          assert.ok(!error.message.includes(root));
          return true;
        });
        for (const artifact of artifacts) {
          if (artifact === path && mutation === "missing") await assert.rejects(readFile(join(root, artifact)));
          else assert.equal(await readFile(join(root, artifact), "utf8"), artifact === path ? "private-artifact-sentinel" : expected(artifact));
        }
      });
    });
  }
}

test("write mode publishes every generated artifact only after successful generation", async () => {
  const generate = await load();
  await fixture(async (root, temporaryParent) => {
    for (const path of artifacts) await put(root, path, "old");
    await generate({ root, temporaryParent, check: false, generateArtifacts: regenerate });
    for (const path of artifacts) assert.equal(await readFile(join(root, path), "utf8"), expected(path));
  });
});

for (const check of [true, false]) {
  for (const failedCategory of artifacts) {
    test(`${check ? "check" : "write"} awaits generator failure at ${failedCategory} and preserves repository`, async () => {
      const generate = await load();
      await fixture(async (root, temporaryParent) => {
        let settled = false;
        await assert.rejects(generate({ root, temporaryParent, check, generateArtifacts: async (output) => {
          for (const path of artifacts) {
            await put(output, path, expected(path));
            if (path === failedCategory) {
              await new Promise((resolve) => setTimeout(resolve, 5));
              settled = true;
              throw new Error("private-generator-error-sentinel");
            }
          }
        } }), (error: Error) => {
          assert.ok(!error.message.includes("private-generator-error-sentinel"));
          return true;
        });
        assert.equal(settled, true);
        for (const path of artifacts) assert.equal(await readFile(join(root, path), "utf8"), expected(path));
      });
    });
  }
}

test("incomplete generated manifest fails before write mode publishes anything", async () => {
  const generate = await load();
  await fixture(async (root, temporaryParent) => {
    await assert.rejects(generate({ root, temporaryParent, check: false, generateArtifacts: async (output) => {
      await put(output, artifacts[0]!, "new");
    } }));
    for (const path of artifacts) assert.equal(await readFile(join(root, path), "utf8"), expected(path));
  });
});

test("real CLI runs all pinned generators from a different working directory without changing artifacts", { timeout: 120000 }, async () => {
  await load();
  const before = await Promise.all(artifacts.map((path) => readFile(join(repository, path))));
  const cwd = await mkdtemp(join(tmpdir(), "flux-generation-cwd-"));
  try {
    const result = spawnSync("bun", [join(repository, "scripts/generate.ts"), "--check"], {
      cwd, env: { ...process.env, TMPDIR: cwd }, encoding: "utf8", timeout: 120000,
    });
    assert.equal(result.status, 0, result.stderr);
    assert.deepEqual(await readdir(cwd), []);
    for (const [index, path] of artifacts.entries()) assert.deepEqual(await readFile(join(repository, path)), before[index]);
  } finally {
    await rm(cwd, { recursive: true, force: true });
  }
});

test("real CLI propagates a nonzero tool exit, hides tool output and cleans partial generation", { timeout: 120000 }, async () => {
  await load();
  const before = await Promise.all(artifacts.map((path) => readFile(join(repository, path))));
  const cwd = await mkdtemp(join(tmpdir(), "flux-generation-failure-"));
  try {
    const bin = join(cwd, "bin");
    await mkdir(bin);
    await writeFile(join(bin, "go"), "#!/bin/sh\nprintf '%s' 'private-tool-output-sentinel'\nexit 17\n");
    await chmod(join(bin, "go"), 0o700);
    for (const mode of [[], ["--check"]]) {
      const result = spawnSync("bun", [join(repository, "scripts/generate.ts"), ...mode], {
        cwd, env: { ...process.env, TMPDIR: cwd, PATH: `${bin}:${process.env.PATH}` }, encoding: "utf8", timeout: 120000,
      });
      assert.equal(result.status, 1);
      assert.equal(result.stdout, "");
      assert.equal(result.stderr.trim(), "Generation failed: tools.lock.json");
      assert.deepEqual(await readdir(cwd), ["bin"]);
      for (const [index, path] of artifacts.entries()) assert.deepEqual(await readFile(join(repository, path)), before[index]);
    }
  } finally {
    await rm(cwd, { recursive: true, force: true });
  }
});
